language: python
python:
- '2.7'
sudo: false
branches:
  only:
  - html5.1-translation-pt
before_install:
- chmod 755 ./.deploy-output.sh
- chmod 755 ./.multipage-split.sh
- nvm install 5.11.1
install:
- pip install pygments cssselect html5lib lxml
- git clone --depth=100 --branch=master https://github.com/tabatkins/bikeshed.git ./bikeshed
# Use stable copy of bikeshed
#- pushd ./bikeshed
#- git checkout 08075e7d3a9fd232f3ab09b4fe8f7b22abfe1345
#- popd
- pip install --editable ./bikeshed
- bikeshed update
# Use cached copy of bikeshed data files to give consistent builds
#- cp -R .spec-data/* ./bikeshed/bikeshed/spec-data
#script: 'bikeshed spec && ./.multipage-split.sh'
script: 'bikeshed -f spec && ./.multipage-split.sh' # @fititnt: force build for now
after_success:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && ./.deploy-output.sh'
env:
  global:
    secure: AzD2Kh9Uw891FYOJDrP6hiNUjs+qhkrCGq3uKy+iHpkveph5JdIGphGVy3e0n5ZQrqJs184OgUUtdvIp7LB014Pg2ZXMy1ePetFZQ9jd9wKoFgkAIZsymJxHNPQbWHvsj1n0sfikcTqGo7XWMM5Kk+trK7LNvd2JtqmFbNDR1xKnK2GTNVue6L4Tw18oKmT6eYMEyDokh1eC2m1F7etbRZO6XCKPxND8zdVU6/JrTHbw8W3lQRp7Pz9lblnrjxtAxdosDxk+vy/DXq1HKMcW4fnqbPC8hwRPmjb4zXrbi17lp4/AIAPdmlFoK8fOvEMKGKfq94ul/IL6p7Y9Qw1bKDtSDErBIut0weA2xbvcpwq4iEBP2bhVACQ/syqVUeEj4RXML/ypAbxCK3Fqr3SAkA17f+4mUh5cLcmGsiZHzt2qJ9Hk+Dgf70gKGWqig7BkStkXkFzpkxtwtPAlRsuW3Ab6zpIXCwXuTiedmBNwbPIskQVQ2rW8dNYU17fQULH/Z9yy5uD1+iZv3xp+0hziTdOAOg6488rn+DGV96WDoGX8yqb6MU+mFnFuVY6ic0Qzj/YmmWFBj02UTsQkytfOgAgPDrzF1KTPYUdkmhvsUQuGnZal2Hm+CbI++6BSOndxopG8Q5CEdpeoQL4e+CnuR34fJI649NwwuFCGpYZgCgU=
